//
// Created by Keshav Bhandari on 2/19/25.
//

/**
 * @file generator.cpp
 * @brief Implementation of functions to generate random solvable Sudoku boards.
 *
 * This file should contain logic to:
 * - Create empty Sudoku boards.
 * - Fill independent diagonal boxes.
 * - Solve the filled board to complete it.
 * - Randomly remove cells to create solvable Sudoku puzzles.
 *
 * @author
 * Keshav Bhandari
 *
 * @date
 * February 7, 2025
 */

#include "../include/generator.h"
#include "../include/sudoku.h"
#include "../include/sudoku_io.h"
#include <random>
#include <bitset>
#include <algorithm>
#include <ctime>
#include <numeric>
#include <iostream>
#include <vector>

using namespace std;

/**
 * @brief Creates an empty 9x9 Sudoku board initialized with zeros.
 * @return int** Dynamically allocated 9x9 board.
 */
int** getEmptyBoard() {
    int** board = new int*[9];
    for(int i = 0; i < 9; i++){
        board[i] = new int[9]{0};
    }
    return board;
}

// Hint 1: Implement a function to return shuffled vectors
/**
 * @brief Returns a vector of numbers 1-9 shuffled randomly.
 * @return std::vector<int> Shuffled numbers from 1 to 9.
 *
 * Example Output: {3, 1, 4, 2, 7, 6, 5, 9, 8}
 */
    vector<int> getShuffledVector() {
    vector<int> vec{1,2,3,4,5,6,7,8,9};
    static mt19937 rng(static_cast<unsigned>(time(nullptr)));
    shuffle(vec.begin(), vec.end(), rng);
    return vec;
}

// Hint 2: Random Independent Box fill
/*
Strategy:
Create a function that takes a BOARD as input, iterates over independent boxes, and fills them with
numbers 1 to 9 using a randomly shuffled vector generated by a helper function.

Example Boards:

Board 1 (Top-Left to Bottom-Right)        Board 2 (Top-Right to Bottom-Left)

+-------+-------+-------+          +-------+-------+-------+
| X X X | . . . | . . . |          | . . . | . . . | X X X |
| X X X | . . . | . . . |          | . . . | . . . | X X X |
| X X X | . . . | . . . |          | . . . | . . . | X X X |
+-------+-------+-------+          +-------+-------+-------+
| . . . | X X X | . . . |          | . . . | X X X | . . . |
| . . . | X X X | . . . |          | . . . | X X X | . . . |
| . . . | X X X | . . . |          | . . . | X X X | . . . |
+-------+-------+-------+          +-------+-------+-------+
| . . . | . . . | X X X |          | X X X | . . . | . . . |
| . . . | . . . | X X X |          | X X X | . . . | . . . |
| . . . | . . . | X X X |          | X X X | . . . | . . . |
+-------+-------+-------+          +-------+-------+-------+

Sample Fill:
Board 1 (Top-Left to Bottom-Right)
+-------+-------+-------+
| 1 5 6 | . . . | . . . |
| 2 4 7 | . . . | . . . |
| 8 3 9 | . . . | . . . |
+-------+-------+-------+
| . . . | 1 7 4 | . . . |
| . . . | 6 2 8 | . . . |
| . . . | 5 9 3 | . . . |
+-------+-------+-------+
| . . . | . . . | 1 6 7 |
| . . . | . . . | 2 5 8 |
| . . . | . . . | 3 4 9 |
+-------+-------+-------+
*/
void fillBoardWithIndependentBox(int** BOARD) {
    for(int box = 0; box < 3; box++) {
        vector<int> numbers = getShuffledVector();
        int startRow = box * 3;
        int startCol = box * 3;
        int idx = 0;
        for(int r = startRow; r < startRow+3; r++) {
            for(int c = startCol; c < startCol+3; c++) {
                BOARD[r][c] = numbers[idx++];
            }
        }
    }
}

// Hint 3: SolveBoard using sudoku.h functions
/*
Example Solve Board:
+-------+-------+-------+
| 1 5 6 | 2 3 7 | 8 9 4 |
| 2 4 7 | 8 1 9 | 5 3 6 |
| 8 3 9 | 4 5 6 | 7 1 2 |
+-------+-------+-------+
| 3 6 2 | 1 7 4 | 9 8 5 |
| 5 9 1 | 6 2 8 | 4 7 3 |
| 7 8 4 | 5 9 3 | 6 2 1 |
+-------+-------+-------+
| 9 2 8 | 3 4 5 | 1 6 7 |
| 4 7 3 | 9 6 1 | 2 5 8 |
| 6 1 5 | 7 8 2 | 3 4 9 |
+-------+-------+-------+
*/

// Hint 4: Create function to randomly delete cells
/**
 * @brief Deletes n unique random cells from the Sudoku board
 * @param BOARD The 9x9 Sudoku board
 * @param n Number of cells to delete (1-81)
 *
 * Example Behavior:
 * - For n = 5, randomly select 5 filled cells and set them to 0
 */
void deleteRandomItems(int** BOARD, const int& n) {
    if(n < 1 || n > 81) {
        cerr << "Invalid number of cells to delete: " << n << endl;
        return;
    }

    vector<int> positions(81);
    iota(positions.begin(), positions.end(), 0);
    static mt19937 rng(static_cast<unsigned>(time(nullptr)));
    shuffle(positions.begin(), positions.end(), rng);

    for(int i = 0; i < n; i++) {
        int pos = positions[i];
        int row = pos / 9;
        int col = pos % 9;
        BOARD[row][col] = 0;
    }
}

/**
 * @brief Generates a solvable Sudoku board with specified empty cells
 * @param empty_boxes Number of empty cells to create
 * @return int** Generated Sudoku board
 *
 * Implementation Steps:
 * 1. Initialize empty board
 * 2. Fill diagonal boxes
 * 3. Solve the board
 * 4. Delete specified number of cells
 */
int** generateBoard(const int& empty_boxes) {
    int** board = getEmptyBoard();
    fillBoardWithIndependentBox(board);

    if(!solve(board, true)) {
        cerr << "Failed to solve generated board" << endl;
        deallocateBoard(board);
        return nullptr;
    }

    deleteRandomItems(board, empty_boxes);
    return board;
}
